### ISSUE TITLE
Issue: Open input Device

### ISSUE THREAD

**Issue by prnk28** [remirobert/RRMessageController#3]
`2015-01-11 20:17:29.697 Floadt[35194:2459976] Error open input device`

I repeatedly get this issue after closing the RRMessageController after the first time. It works swimmingly the first time but after that it fails to open and shows this issue. This is on the iOS simulator.

**Comment by remirobert** [comment]
Hi, that à normal, because i use avfoundation do you need à real device with à caméra. I Will make my possible to fix it.
