### ISSUE TITLE
Show and use camera icon?

### ISSUE THREAD

**Issue by Vivanda** [remirobert/RRMessageController#4]
How can one add and use the camera or at least the image picker to attach images to posts? I think it's possible but don't know how. Would you mind to provide an example. Thx!

**Comment by remirobert** [comment]
Sorry i don't know what you mean. RRMessageController allows you to pick a picture directly from the camera, or your library. It's already implemented. 

But be careful i noticed, there is a bug in the example demo, the camera icon picture is missing. So you can see the button, it is there !. Try to clic and you will see. You can look the gif on the README for a real example. 


Enjoy RRMessageController, and coding  !

**Comment by Vivanda** [comment]
Oh. That's what I was curious about. I saw the image in your demo but can't see it in my app. How do I make it appear? Do I have to do anything in addition?

**Comment by Vivanda** [comment]
Also, how to change the font size of the text view? the current font is really small.

**Comment by remirobert** [comment]
Normally, the selected images are displayed above the keyboard or the image picker. If it's not, there is a bug.

TextView
=======
For change the UITextView font size, you can do it easy, the **initTextView** method (**line 465**).
And there add your customisation about your textView.

Bugs
====
Can you post a screen here of your bug ? If so i will fix it.

**Comment by Vivanda** [comment]
Very strange behavior. I don't see any camera icon but sometimes by clicking somewhere in the left area of the gray bar below the text window either the camera or the image picker one up. In latter one I can select images, which then appear above but there is no way to delete any of these from the selection again.


![img_0159](https://cloud.githubusercontent.com/assets/10742638/6503953/105cb0de-c332-11e4-9939-b39e04b7dc68.PNG)
![img_0160](https://cloud.githubusercontent.com/assets/10742638/6503952/105c6610-c332-11e4-8f18-b9e5428017db.PNG)
![img_0161](https://cloud.githubusercontent.com/assets/10742638/6503954/105d7384-c332-11e4-92aa-701fed96fdc2.PNG)

**Comment by Vivanda** [comment]
I played more and believe your issue is with the new keyboard in iOS8.x - the quick type part above the keyboard (guessing words) modifies the gray area you have set for your controls. Somewhere there your camera button and actions seem to sit? hope that helps

**Comment by remirobert** [comment]
the example project is not updated. I will push a new version.
Thanks for your help.
